# Generated by Django 5.0 on 2024-02-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='facultyRegister',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('uname', models.CharField(max_length=30, unique=True)),
                ('kmail', models.CharField(max_length=30, unique=True)),
                ('did', models.CharField(max_length=30)),
                ('dname', models.CharField(max_length=30)),
                ('pword', models.CharField(max_length=12)),
                ('pnumber', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'facultyregister_table',
            },
        ),
        migrations.AlterField(
            model_name='register',
            name='departmentName',
            field=models.CharField(max_length=30),
        ),
    ]
