# Generated by Django 5.0 on 2024-03-08 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'exam_type',
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('branch', models.CharField(max_length=50)),
                ('max_marks', models.IntegerField()),
                ('marks_obtained', models.IntegerField()),
                ('remarks', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.course')),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.examtype')),
            ],
            options={
                'db_table': 'exam_result',
            },
        ),
        migrations.AlterField(
            model_name='examresult',
            name='id',
            field=models.CharField(max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
