# Generated by Django 5.0.3 on 2024-03-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_department_examtype_examresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
